apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoimage
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.demo-app: semver:~1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoimage
  template:
    metadata:
      labels:
        app: demoimage
    spec:
      containers:
      - name: demoimage
        image: shivamg202/demoimage
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
