apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ acc.IMAGE_NAME }}
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.demo-app: semver:~1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${{ acc.IMAGE_NAME }}
  template:
    metadata:
      labels:
        app: ${{ acc.IMAGE_NAME }}
    spec:
      containers:
      - name: ${{ acc.IMAGE_NAME }}
        image: ${{ acc.DOCKER_USERNAME }}/${{ acc.IMAGE_NAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
